### ISSUE TITLE
ZLogFactory tries to instantiate non-existant class "org.gridkit.zerormi.zlog.Slf4JLogger"

### ISSUE THREAD

**Issue by sannam888** [gridkit/nanocloud#10]
ZLogFactory tries to instantiate non-existant class "org.gridkit.zerormi.zlog.Slf4JLogger", I believe the correct class should be "org.gridkit.zerormi.zlog.ZLogToSlf4J"

**Comment by aragozin** [comment]
Indeed, master is fixed now. Though, I do not have a date for next release yet.
