### ISSUE TITLE
Several nodes at one remote host without modifying hosts file

### ISSUE THREAD

**Issue by askogvold** [gridkit/nanocloud#14]
Hi

Is this supported out of the box?

If not, I suggest adding support for @ in host name to separate multiple nodes,

e.g. 
p1@otherHost
p2@otherHost

**Comment by askogvold** [comment]
Managed to work around this with `RemoteNode.at(cloud.node("p2")).setRemoteHost("otherHost")`

**Comment by aragozin** [comment]
hostname == nodeId is mostly for "hello world" case.

By default remote host property is set to 

    ~%s!(.*) 

`~` - means it is a template
`%s` - format string, arguments are matching groups produced by applying regex to node ID 
`!` - magic separator
`(.*)` - Java regex

If you want p1@host to be mapped to host.acme.com you can use snippet below

    RemoteNode.at(cloud.node("**")).setRemoteHost("~%s.acme.com![^@]*[@](.*)")

Though, mapping nodes to hosts explicitly is also valid option useful sometimes

**Comment by askogvold** [comment]
Nice! Thanks
