### ISSUE TITLE
CGLIB-wrapped classes(in runtime) cannot be loaded and throw ClassNotFoundException

### ISSUE THREAD

**Issue by ruzovvo** [gridkit/nanocloud#18]
https://github.com/gridkit/nanocloud/blob/9fd48e0be5a6b3083e18333109cd8b2ed118e0ac/vicluster-core/src/main/java/org/gridkit/vicluster/isolate/Isolate.java#L1819

Spring context wraps some classes with EnhancerByCGLIB. After writing a new class it's defined in a classLoader in net.sf.cglib.core.AbstactClassGenerator#create() method (line 219). But this is 'define' method is a method from ClassLoader, so this class cannot be found in any URL. 
IsolateClassLoader should check super.loadClass() before throwing an exception

**Comment by aragozin** [comment]
Delegating to parent classloader would break class isolation and likely to cause class linkage errors.
If you can share minimal example reproducing this problem, that would help.

**Comment by aragozin** [comment]
Fixed in 0.8.14
